
name: Task -1 (Lint, Test & Deploy)

on: 
    push:
        branches:
            - main
            - feature/*

jobs:
  Lint_Test_Deploy:  
    name: Lint_Test_Deploy
    runs-on: ubuntu-latest
    steps:
        # 1. Checkout to the repo code
        - name: Checkout Repository
          uses: actions/checkout@v4

        # 2. Install npm
        - name: Install dependencies
          run: npm install

        # 3. Run lint
        - name: check the lint 
          run: npm run lint

        # 4. run test
        - name: Test the code
          run: npm run test

        # 5. run build
        - name: Build the code
          run: npm run build
        
        


